### PR TITLE
Enable wayland backend

### PR DESCRIPTION
**Pull request by Twig6943**

### CODE REVIEW

**Comment by hfiguiere** [comment]
why did you open a new PR?

**Comment by Twig6943** [comment]
> why did you open a new PR?

Previous one failed

**Comment by Twig6943** [comment]
The wayland backend seems to work fine. Pls merge
Wayland

**Comment by hfiguiere** [comment]
> > why did you open a new PR?
> 
> Previous one failed

there was not reason to do so.

**Comment by Twig6943** [comment]
> > > why did you open a new PR?
> > 
> > 
> > Previous one failed
> 
> there was no reason to do so.

yea thats just how I do (Im stupid as hell ik)

anyways merge or pass?

**Comment by Twig6943** [comment]
> > > > why did you open a new PR?
> > > 
> > > 
> > > Previous one failed
> > 
> > 
> > there was no reason to do so.
> 
> yea thats just how I do (Im stupid as hell ik)
> 
> anyways merge or pass?

Its been a good while since this https://github.com/flathub/io.github.OpenToonz/pull/13#issuecomment-842750330

**Comment by hfiguiere** [comment]
you didn't test it on a wayland system.

```
$ flatpak run --nosocket=x11 --socket=wayland io.github.OpenToonz
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.qgnomeplatform: Could not find color scheme  ""
freeglut (/app/bin/../bin/OpenToonz): failed to open display ''
```

**Comment by hfiguiere** [comment]
what this is showing that X11 is there too. Not the fallback. Once again you didn't test properly. This PR does break OpenToonz as you second guess the maintainers.

**Comment by hfiguiere** [comment]
if you checked with xprop then it's a X11 window. And the permission window you show so prominently show it has X11 access, which is not the same as the PR.

But what do I know?

**Comment by Twig6943** [comment]
"I've also checked with xprop"
XProp didnt detect the window. Thats what I meant. Im absolutely sure that I got a wayland window

**Comment by Twig6943** [comment]
Update:
https://github.com/user-attachments/assets/dd1b0941-45be-4da7-aa36-2a0221a69328

**Comment by Twig6943** [comment]
@hfiguiere do u have me blocked? (like I said I'm sorry for the whole thing)

**Pull request closed without merging**
